name: CI
on: [ push ]

jobs:
  build_hello_world_application:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: Building hello_world_application
        shell: bash
        working-directory: hello_world_application
        run: |
          cmake -B ./build
          cd build
          make
          ./hello_world

  build_sovler_application:
    runs-on: ubuntu-latest

    steps:
        - name: checkout
          uses: actions/checkout@master

        - name: Building solver_application
          shell: bash
          working-directory: solver_application
          run: |
            cmake -B ./build
            cd build
            make
            ./equation
        - name: packaging solver_application
          shell: bash
          working-directory: solver_application
          run: |
            cd build
            make package
            make package_source